export UCP_REPO_PATH=${UCP_REPO_PATH:-vendor/unified-control-plane}
export SKIP_UCP_INSTALL=${SKIP_UCP_INSTALL:-0}

export BACKSTAGE_REPO_PATH=${BACKSTAGE_REPO_PATH:-vendor/backstage}
export SKIP_BACKSTAGE_INSTALL=${SKIP_BACKSTAGE_INSTALL:-0}

export BACKSTAGE_TEMPLATE_GEN_PATH=${BACKSTAGE_TEMPLATE_GEN_PATH:-vendor/backstage-template-gen-go}
export SKIP_BACKSTAGE_TEMPLATE_GEN_BUILD=${SKIP_BACKSTAGE_TEMPLATE_GEN_BUILD:-0}

export FORCE_BACKSTAGE_SA_INSTALL=${FORCE_BACKSTAGE_SA_INSTALL:-1}
